#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to redirect requests

# Update package manager / install server 
echo -e "installing Nginx... sit back and relax....\n"
sudo apt-get update
sudo apt-get install -y nginx

# redirect to another page
replace_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/mattfarley.ca permanent;"
sudo sed -i "s/server_name _;/$replace_string/" /etc/nginx/sites-enabled/default

# Add 'Hello World!' text to index file
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# restart Nginx server
sudo service nginx restart
echo -e "Succesfully installed Nginx.. enjoy....\n"
