#!/usr/bin/env bash

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

## Configure Nginx

# Create the HTML directory
mkdir -p /etc/nginx/html

# Create the index.html file and add content
echo "Hello World!" > /etc/nginx/html/index.html

# Modify the Nginx configuration file
sed -i '/location \/redirect_me/,+1 d' /etc/nginx/sites-available/default
sed -i '/server {/a \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }\
' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
systemctl restart nginx

