#!/usr/bin/env bash

#  script that pings an IP address passed as an argument. Requirements:
#+ Accepts a string as an argument
#+ Displays 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}' if no argument passed
#+ Pings the IP 5 times

# Check if an argument was passed
if [ "$#" -ne 1 ]; then
    echo "Usage:  5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ip_address=$1

ping -c 5 $ip_address
