#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.
#+ In between each iteration of the loop, add a sleep 2

infinity=0

while [ $infinity -eq 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done
