#!/usr/bin/env bash
# script that stops 4-to_infinity_and_beyond process.
#+ You must use kill

# infinity=0

# while [ $infinity -eq 0 ]; do
#     echo "To infinity and beyond"
#     sleep 2
# done

pkill -f "4-to_infinity_and_beyond"
