#!/usr/bin/env bash
# print I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
infinity=0

while [ $infinity -eq 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done
