#!/usr/bin/env bash

# script that displays: The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed

for file in *; do
    # Check if the file is not a hidden file (doesn't start with a dot)
    if [[ ! "$file" == .* ]]; then
        # Extract the part of the name after the first dash
        # -f2- means start from second field onward
        part_name=$(echo "$file" | cut -d'-' -f2-)
        
        # Display the modified name
        echo "$part_name"
    fi
done
# added comment to recall what the characters does
