#!/usr/bin/env bash 
#A script to change your home IP
#Changes the localHost - 127.0.0.2 and Facebook.com - 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2 localhost\n8.8.8.8 \t facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
