#!/usr/bin/env bash
# configuration of ssh server to login without
# password

Host 343458-web-01
    HostName 34.203.75.104
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
